### ISSUE TITLE
Versión mejorada

### ISSUE THREAD

**Issue by joelmzj** [Devil64-Dev/My-Platzi-Downloader#1]
La versión mejorada ya no está disponoble. :(

**Comment by Devil64-Dev** [comment]
Si, debido a el error 404 que entrega platzi.com como respuesta a la petitcion de autenticación se volvio inutil.
Pero si necesitas bajar cursos de platzi.com response a este comentario y te mando el link de una nueva versión.

**Comment by Devil64-Dev** [comment]
Este es el nuevo: https://github.com/Devil64-Dev/platzi-dtool,
no se si sera por que ahora no cuento con un plan, pero youtube-dl dejo de funcionar como lo hacia antes, así que este lo hice para que funcionara a la fuerza, no te dara muchos problemas si haces los pasos de configuración como se muestran el video.
